#![allow(non_camel_case_types)]
#![allow(dead_code)]

use std::ops::RangeInclusive;

use crate::{builder::VecLike, MsgBuilder};

#[allow(clippy::len_without_is_empty)]
pub trait IntoEvent {
    const LEN: RangeInclusive<Option<usize>>;

    fn len(&self) -> usize;
    fn encode<V: VecLike>(self, v: &mut MsgBuilder<V>);
}

impl IntoEvent for Event {
    const LEN: RangeInclusive<Option<usize>> = Some(1)..=Some(1);

    fn len(&self) -> usize {
        1
    }

    fn encode<V: VecLike>(self, v: &mut MsgBuilder<V>) {
        v.msg.add_element(self as u8)
    }
}

impl<S: AsRef<str>> IntoEvent for S {
    const LEN: RangeInclusive<Option<usize>> = Some(2)..=None;

    fn len(&self) -> usize {
        self.as_ref().len()
    }

    fn encode<V: VecLike>(self, v: &mut MsgBuilder<V>) {
        v.msg.add_element(255);
        v.encode_str(format_args!("{}", self.as_ref()));
    }
}

pub enum Event {
    abort,
    activate,
    addstream,
    addtrack,
    afterprint,
    afterscriptexecute,
    animationcancel,
    animationend,
    animationiteration,
    animationstart,
    appinstalled,
    audioend,
    audioprocess,
    audiostart,
    auxclick,
    beforeinput,
    beforeprint,
    beforescriptexecute,
    beforeunload,
    beginEvent,
    blocked,
    blur,
    boundary,
    bufferedamountlow,
    cancel,
    canplay,
    canplaythrough,
    change,
    click,
    close,
    closing,
    complete,
    compositionend,
    compositionstart,
    compositionupdate,
    connect,
    connectionstatechange,
    contentdelete,
    contextmenu,
    copy,
    cuechange,
    cut,
    datachannel,
    dblclick,
    devicechange,
    devicemotion,
    deviceorientation,
    DOMActivate,
    DOMContentLoaded,
    DOMMouseScroll,
    drag,
    dragend,
    dragenter,
    dragleave,
    dragover,
    dragstart,
    drop,
    durationchange,
    emptied,
    end,
    ended,
    endEvent,
    enterpictureinpicture,
    error,
    focus,
    focusin,
    focusout,
    formdata,
    fullscreenchange,
    fullscreenerror,
    gamepadconnected,
    gamepaddisconnected,
    gatheringstatechange,
    gesturechange,
    gestureend,
    gesturestart,
    gotpointercapture,
    hashchange,
    icecandidate,
    icecandidateerror,
    iceconnectionstatechange,
    icegatheringstatechange,
    input,
    inputsourceschange,
    install,
    invalid,
    keydown,
    keypress,
    keyup,
    languagechange,
    leavepictureinpicture,
    load,
    loadeddata,
    loadedmetadata,
    loadend,
    loadstart,
    lostpointercapture,
    mark,
    merchantvalidation,
    message,
    messageerror,
    mousedown,
    mouseenter,
    mouseleave,
    mousemove,
    mouseout,
    mouseover,
    mouseup,
    mousewheel,
    msContentZoom,
    MSGestureChange,
    MSGestureEnd,
    MSGestureHold,
    MSGestureStart,
    MSGestureTap,
    MSInertiaStart,
    MSManipulationStateChanged,
    mute,
    negotiationneeded,
    nomatch,
    notificationclick,
    offline,
    online,
    open,
    orientationchange,
    pagehide,
    pageshow,
    paste,
    pause,
    payerdetailchange,
    paymentmethodchange,
    play,
    playing,
    pointercancel,
    pointerdown,
    pointerenter,
    pointerleave,
    pointerlockchange,
    pointerlockerror,
    pointermove,
    pointerout,
    pointerover,
    pointerup,
    popstate,
    progress,
    push,
    pushsubscriptionchange,
    ratechange,
    readystatechange,
    rejectionhandled,
    removestream,
    removetrack,
    removeTrack,
    repeatEvent,
    reset,
    resize,
    resourcetimingbufferfull,
    result,
    resume,
    scroll,
    search,
    seeked,
    seeking,
    select,
    selectedcandidatepairchange,
    selectend,
    selectionchange,
    selectstart,
    shippingaddresschange,
    shippingoptionchange,
    show,
    signalingstatechange,
    slotchange,
    soundend,
    soundstart,
    speechend,
    speechstart,
    squeeze,
    squeezeend,
    squeezestart,
    stalled,
    start,
    statechange,
    storage,
    submit,
    success,
    suspend,
    timeout,
    timeupdate,
    toggle,
    tonechange,
    touchcancel,
    touchend,
    touchmove,
    touchstart,
    track,
    transitioncancel,
    transitionend,
    transitionrun,
    transitionstart,
    unhandledrejection,
    unload,
    unmute,
    upgradeneeded,
    versionchange,
    visibilitychange,
    voiceschanged,
    volumechange,
    vrdisplayactivate,
    vrdisplayblur,
    vrdisplayconnect,
    vrdisplaydeactivate,
    vrdisplaydisconnect,
    vrdisplayfocus,
    vrdisplaypointerrestricted,
    vrdisplaypointerunrestricted,
    vrdisplaypresentchange,
    waiting,
    webglcontextcreationerror,
    webglcontextlost,
    webglcontextrestored,
    webkitmouseforcechanged,
    webkitmouseforcedown,
    webkitmouseforceup,
    webkitmouseforcewillbegin,
    wheel,
}
